version: 2
jobs:
  build:
    docker:
      - image: circleci/build-image
    steps:
      - setup_remote_docker:   # (2)
          docker_layer_caching: true # (3)
      - run:
          name: GET Dockerfile 
          command: wget https://raw.githubusercontent.com/minepicco/speechtotext-dockerfile/master/Dockerfile -O Dockerfile
      - run:
          name: docker ps
          command: docker ps -a

      - run:
          name: build
          command: docker build -t minepicco/test:1.0 .
  test:
    docker:
      - image: circleci/build-image
    steps:
      - run:
          name: docker login
          command: docker login -u $username -p $password -e $mailaddress
     
      - run:
          name: docker push
          command: docker push minepicco/test:1.0
          
